services:
  - type: web
    name: MiniCore_MR
    runtime: docker
    buildCommand: dotnet publish -c Release -o publish
    startCommand: dotnet MiniCore_MR.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-comisiones
          property: connectionString